name: exo_hunter
description: "Hunting Exoplanets with AI - A Flutter application for discovering worlds beyond our solar system."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.1.1

  # Authentication - Updated to latest compatible versions
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.3

  # HTTP requests
  # http: ^1.1.2
  # dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # OPTIMIZED ASSETS
  assets:
    - assets/cosmic_bg.png
    - assets/logo.png

  # OPTIMIZED FONTS - Only include necessary font weights
  fonts:
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron/static/Orbitron-Regular.ttf
          weight: 400
        - asset: fonts/Orbitron/static/Orbitron-Bold.ttf
          weight: 700

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo.png"


# sheikhsiamnajat